apiVersion: v1
kind: Service
metadata:
 name: enterprise-app-service
 namespace: enterprise-app
spec:
 type: NodePort
 selector:
  app: enterprise-app
 ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    